name: Release Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies  
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: NugetPack
      run: dotnet pack --configuration Release 
      working-directory: ${{env.working-directory}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{env.working-directory}}/ReflectionMapper/bin/Release/*
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.3.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ${{env.working-directory}}/ReflectionMapper/ReflectionMapper.csproj
        # Flag to enable / disable git tagging
        TAG_COMMIT: true # optional, default is true
        # Format of the git tag, `[*]` gets replaced with version
        TAG_FORMAT: v* # optional, default is v*
        # API key for the NuGet feed
        NUGET_KEY:  ${{secrets.nuget_reflectionmapper}}  # optional
